RDKBACCL-1533 : Observing build issues in tip (i,e Mar18)
Reason for change: Observing below errors
source/core/services/vap_svc_mesh_ext.c:742: undefined reference to `wifi_hal_rnr_init'
| collect2: error: ld returned 1 exit status
this issue is caused by https://github.com/rdkcentral/rdk-wifi-hal/pull/613
Test Procedure: Build is successful
Risks: Low

Signed-off-by: keerthana.p <keerthana_pandurangan@comcast.com>